# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  release:
    types: [ created ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update repository
        run: sudo yum update -y

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name:  Java installation
        run: sudo yum install java-1.8.0 -y
      - name: Java version
        run: java -version
      - name: yum utils installation
        run: sudo yum install -y yum-utils
      - name: Add repo to config manager
        run: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - name: terraform installation
        run: sudo yum -y install terraform
      - name: Terraform version
        run: terraform --version
      - name: Initializing Terraform
        working-directory: /home/ec2-user/project1
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"
      - name: Initialize terraform
        run: terraform init
      - name: Plan terraform
        run: terraform plan
      - name: Appying terraform
        run: terraform apply --auto-approve
